name: deploy to ConoHa WING

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: install
        - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: build
        - name: ssh key generate
          run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: rsync deployments
          uses: burnett01/rsync-deployments@5.1
          with:
            switches: -avz --delete
            path: dist/
            remote_path: ${{ secrets./home/c8541067/public_html/tree-identification-app.conohawing.com/ }}
            remote_host: ${{ secrets.www313.conoha.ne.jp }}
            remote_user: ${{ secrets.c8541067 }}
            remote_port: ${{ secrets.8022 }}
            remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
